emailService:
  smtp: 'smtp.gmail.com'
  authentication:
    user: ''
    pass: ''
reminderEmail:
  enabled: false
  content:
    from: ''
    to: ''
    cc: ''
  schedule: '00 * * * * *'
  emailListFilePath: 'db/data/email-list-example.csv'
